modLoader="lowcodefml"
loaderVersion="*"
issueTrackerURL="https://github.com/Xenon372/TinkersKatanas/issues"
license="MIT"
[[mods]]
    modId="tinkers_katanas"
    version="1.3.8"
    displayName="Tinkers' Katanas"
    description='''
    A Thing Pack for Tinkers' Construct.
    '''
[[dependencies.tinkers_katanas]]
    modId="tconstruct"
    mandatory=true
    versionRange="[3.9.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkers_katanas]]
    modId="jsonthings"
    mandatory=true
    versionRange="[0.9.9,)"
    ordering="NONE"
    side="BOTH"

